spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:car}?currentSchema=${DB_SCHEMA:public}
        username: ${DB_USER:postgres}
        password: ${DB_PASS:postgres}
    jpa:
        hibernate.ddl-auto: update
        open-in-view: false
    flyway:
        baseline-description: true
        baseline-on-migrate: true
        create-schemas: true
        default-schema: public
        enabled: true
        locations: classpath:db/migration
        schemas: public
        validate-on-migrate: true
        validate-migration-naming: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
