CREATE TABLE IF NOT EXISTS categories (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_name varchar(255) NOT NULL,
    CONSTRAINT pk_categories_id PRIMARY KEY (id),
    CONSTRAINT unique_categories_category_name UNIQUE (category_name)
);

INSERT INTO categories (category_name) VALUES
   ('M1'),
   ('M2'),
   ('M3'),
   ('N1'),
   ('N2'),
   ('N3'),
   ('O1'),
   ('02'),
   ('O3'),
   ('O4');
