CREATE TABLE IF NOT EXISTS registration_numbers (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    registration_number varchar(255) NOT NULL,
    CONSTRAINT pk_registration_numbers_id PRIMARY KEY (id),
    CONSTRAINT unique_registration_numbers_registration_number UNIQUE (registration_number)
);

INSERT INTO registration_numbers (registration_number) VALUES
       ('А001ВС'),
       ('Е999КХ'),
       ('0124ВМ'),
       ('Т555ОТ'),
       ('М028МР'),
       ('У700УН');
