CREATE TABLE IF NOT EXISTS transport_types (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type_name varchar(255) NOT NULL,
    CONSTRAINT pk_transport_types_id PRIMARY KEY (id),
    CONSTRAINT unique_transport_types_type_name UNIQUE (type_name)
);

INSERT INTO transport_types (type_name) VALUES
   ('Седан'),
   ('Хэтчбек'),
   ('Универсал'),
   ('Кабриолет'),
   ('Кроссовер'),
   ('Купе'),
   ('Лимузин');
