CREATE TABLE IF NOT EXISTS vehicles (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    make varchar(255) NOT NULL,
    model varchar(255) NOT NULL,
    category_id int8 NOT NULL,
    registration_number_id int8 NOT NULL,
    transport_type_id int8 NOT NULL,
    year INT NOT NULL,
    trailer_available bool NOT NULL,
    CONSTRAINT pk_vehicles_id PRIMARY KEY (id),
    CONSTRAINT unique_vehicles_registration_number_id UNIQUE (registration_number_id),
    CONSTRAINT fk_vehicles_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_vehicles_registration_number FOREIGN KEY (registration_number_id) REFERENCES registration_numbers(id),
    CONSTRAINT fk_vehicles_transport_type FOREIGN KEY (transport_type_id) REFERENCES transport_types(id)
);

INSERT INTO vehicles (make, model, category_id, registration_number_id, transport_type_id, year, trailer_available)
VALUES ('Toyota', 'Camry', 1, 1, 1, 2022, false);

INSERT INTO vehicles (make, model, category_id, registration_number_id, transport_type_id, year, trailer_available)
VALUES ('Toyota', 'MARK2', 2, 2, 3, 1990, true);

INSERT INTO vehicles (make, model, category_id, registration_number_id, transport_type_id, year, trailer_available)
VALUES ('Nissan', 'Skyline', 3, 3, 3, 1990, true);
